// tools/src/extract/routes.rs
//
// Emits routes.json and routes.d.ts from all ExtractedSpec entries.
// Warns to stderr when duplicate route patterns are detected.

use std::collections::HashSet;
use std::path::Path;

use crate::types::ExtractedSpec;

/// A single route record written into routes.json.
#[derive(serde::Serialize)]
struct RouteRecord<'a> {
  tag: &'a str,
  path: &'a str,
  #[serde(skip_serializing_if = "Option::is_none")]
  container: Option<&'a str>,
  /// Ordered container chain (root-to-leaf) a page renders through.
  #[serde(skip_serializing_if = "Vec::is_empty")]
  via: &'a Vec<String>,
  params: Vec<String>,
}

fn to_pascal_case(s: &str) -> String {
  let mut result = String::new();
  let mut capitalize = true;
  for c in s.chars() {
    if c == '-' || c == '_' || c == ':' {
      capitalize = true;
    } else if capitalize {
      result.extend(c.to_uppercase());
      capitalize = false;
    } else {
      result.push(c);
    }
  }
  result
}

/// Emits `routes.json` and `routes.d.ts` files to `dist_dir`.
pub fn emit(specs: &[(std::path::PathBuf, ExtractedSpec)], dist_dir: &Path) {
  let mut records: Vec<RouteRecord> = Vec::new();
  let mut seen: HashSet<String> = HashSet::new();

  let mut route_map_entries = Vec::new();
  let mut element_interfaces = Vec::new();
  let mut tag_mappings = Vec::new();

  for (_path, spec) in specs {
    // Collect types information for element
    let class_name = format!("{}Element", to_pascal_case(&spec.tag));
    let mut props_decl = Vec::new();
    for (prop_name, prop_config) in &spec.props {
      let ts_type = match prop_config.prop_type.as_str() {
        "boolean" => "boolean",
        "number" => "number",
        "string" => "string",
        _ => "any",
      };
      props_decl.push(format!("  {}: {};", prop_name, ts_type));
    }

    let mut methods_decl = Vec::new();
    for method_name in &spec.methods {
      methods_decl.push(format!("  {}(...args: any[]): any;", method_name));
    }

    // A dock exposes the router-driven swap method for content replacement.
    if spec.kind == "dock" {
      methods_decl.push(
        "  swap(el: HTMLElement, options?: { direction?: string }): Promise<void>;".to_string()
      );
    }

    element_interfaces.push(format!(
      "export interface {} extends HTMLElement {{\n{}\n{}\n}}",
      class_name,
      props_decl.join("\n"),
      methods_decl.join("\n")
    ));

    tag_mappings.push(format!("    \"{}\": {};", spec.tag, class_name));

    // Check if route url is declared
    let url = match &spec.url {
      Some(u) if !u.is_empty() => u.as_str(),
      _ => continue,
    };

    if !seen.insert(url.to_string()) {
      eprintln!(
        "[anza] WARNING: Duplicate route pattern \"{}\" defined on <{}>.",
        url, spec.tag
      );
    }

    let params = extract_params(url);

    records.push(RouteRecord {
      tag: &spec.tag,
      path: url,
      container: spec.container.as_deref(),
      via: &spec.via,
      params,
    });

    let container_str = match &spec.container {
      Some(c) => format!("container: \"{}\"", c),
      None => "container?: never".to_string(),
    };

    let mut meta_pairs = Vec::new();
    for (k, v) in &spec.meta {
      if v == "true" || v == "false" {
        meta_pairs.push(format!("\"{}\": {}", k, v));
      } else if v.parse::<f64>().is_ok() {
        meta_pairs.push(format!("\"{}\": {}", k, v));
      } else {
        meta_pairs.push(format!("\"{}\": \"{}\"", k, v));
      }
    }
    let meta_str = if meta_pairs.is_empty() {
      "meta: {}".to_string()
    } else {
      format!("meta: {{ {} }}", meta_pairs.join(", "))
    };

    route_map_entries.push(format!(
      "  \"{}\": {{ {}, {} }};",
      url, container_str, meta_str
    ));
  }

  // Write routes.json
  let output = serde_json::json!({
    "version": 1,
    "routes": records,
  });

  std::fs::create_dir_all(dist_dir).ok();
  let dest_json = dist_dir.join("routes.json");

  match serde_json::to_string_pretty(&output) {
    Ok(json) => {
      std::fs::write(&dest_json, json).ok();
      logs::success!("Route manifest written to {}", dest_json.display());
    }
    Err(err) => {
      eprintln!(
        "[anza] ERROR: Failed to serialize routes.json: {}",
        err
      );
    }
  }

  // Write routes.d.ts
  let dts_content = format!(
    r#"/**
 * routes.d.ts
 *
 * Automatically generated by anza. Do not edit manually.
 */

export interface RouteMeta {{
  title?: string;
  auth?: boolean;
  [key: string]: any;
}}

export interface RouteMap {{
{}
}}

{}

declare global {{
  interface HTMLElementTagNameMap {{
{}
  }}
}}
"#,
    route_map_entries.join("\n"),
    element_interfaces.join("\n\n"),
    tag_mappings.join("\n")
  );

  let dest_dts = dist_dir.join("routes.d.ts");
  if std::fs::write(&dest_dts, dts_content).is_ok() {
    logs::success!("Route type declarations written to {}", dest_dts.display());
  }
}

/// Extracts named URLPattern param names from a path pattern string.
/// e.g. "/members/:member/posts/:post" -> ["member", "post"]
fn extract_params(pattern: &str) -> Vec<String> {
  let mut params = Vec::new();
  for segment in pattern.split('/') {
    if let Some(name) = segment.strip_prefix(':') {
      // Strip any trailing modifier characters like ? + *
      let clean = name.trim_end_matches(|c| c == '?' || c == '+' || c == '*');
      if !clean.is_empty() {
        params.push(clean.to_string());
      }
    }
  }
  params
}
