// tools/src/extract/runner.rs

use std::collections::HashMap;
use std::path::Path;
use std::sync::Arc;
use walkdir::WalkDir;

use swc_common::SourceMap;
use swc_ecma_ast::*;
use swc_ecma_parser::{lexer::Lexer, Parser, StringInput, Syntax};
use swc_ecma_visit::{Visit, VisitWith};

use crate::types::{ExtractedSpec, PropConfig};

/// Consolidated build compilation stage.
///
/// `strict` controls error handling: in build mode a failed import-graph
/// resolution aborts the process (no partial dist is published); in dev mode
/// the errors are logged and the last good dist is kept.
pub fn build(src_dir: &Path, dist_dir: &Path, entries: &[std::path::PathBuf]) {
  compile(src_dir, dist_dir, true, entries);
}

/// Non-fatal compile used by the dev pipeline.
pub fn compile(
  src_dir: &Path,
  dist_dir: &Path,
  strict: bool,
  entries: &[std::path::PathBuf],
) {
  let types_dir = dist_dir.join("types");

  // Production build: start from a clean slate so deleted source files
  // never linger in the output. Dev mode keeps the old dist alive — the
  // hash cache handles incremental copies and the browser never gets 404s.
  if strict && dist_dir.exists() {
    std::fs::remove_dir_all(dist_dir).ok();
  }
  std::fs::create_dir_all(dist_dir).ok();

  // 2. Type/route/tag extraction (writes dist/types, dist/routes.json,
  //    and .tags.json siblings in src).
  run(src_dir, &types_dir);

  // 3. Import-graph resolution -> minimal, browser-native dist.
  match crate::build::resolve(src_dir, dist_dir, entries, !strict) {
    Ok(report) => {
      for w in &report.warnings {
        crate::build::graph::report_line(w);
      }
      logs::success!(
        "Resolved {} modules -> {} files copied into {}",
        report.modules,
        report.copied,
        dist_dir.display()
      );
    }
    Err(diags) => {
      for d in &diags {
        crate::build::graph::report_line(d);
      }
      logs::error!("Build failed: {} error(s) in the import graph", diags.len());
      if strict {
        // Do not publish a partial dist on a failed build.
        std::fs::remove_dir_all(dist_dir).ok();
        std::process::exit(1);
      }
    }
  }
}

pub fn run(src_dir: &Path, dist_types_dir: &Path) {
  // Collect all paths to parallelize with Rayon
  let paths: Vec<_> = WalkDir::new(src_dir)
    .into_iter()
    .filter_map(|e| e.ok())
    .filter(|e| e.file_type().is_file())
    .map(|e| e.path().to_path_buf())
    .collect();

  let cm = Arc::new(SourceMap::default());

  use rayon::prelude::*;

  // Parallel walk & parse — import graph handles element selection naturally
  let specs: Vec<(std::path::PathBuf, ExtractedSpec)> = paths
    .par_iter()
    .filter_map(|path| {
      if path.extension().map_or(false, |ext| ext == "js") {
        parse_element_file(path, &cm).map(|spec| (path.clone(), spec))
      } else if path.extension().map_or(false, |ext| ext == "html") {
        logs::compiler!("Found HTML: {:?}", path);
        if let Err(err) = super::html::parse_and_emit(path) {
          logs::error!("Failed to generate tags descriptor for {:?}: {}", path, err);
        }
        None
      } else {
        None
      }
    })
    .collect();

  // 2. Write individual .d.ts files and the main index.d.ts
  std::fs::create_dir_all(dist_types_dir).ok();

  let mut global_typings = String::new();
  global_typings.push_str("/* Auto-generated by anza. Do not edit. */\n\n");
  global_typings.push_str("declare global {\n  interface HTMLElementTagNameMap {\n");

  for (file_path, spec) in &specs {
    let relative_path = file_path.strip_prefix(src_dir).unwrap_or(file_path);
    let mut type_path = dist_types_dir.join(relative_path);
    type_path.set_extension("d.ts");
    if let Some(parent) = type_path.parent() {
      std::fs::create_dir_all(parent).ok();
    }

    // Write the custom element interface declaration
    let dts_content = generate_dts_content(spec);
    std::fs::write(&type_path, dts_content).ok();

    // Add to global HTMLElementTagNameMap augmentation
    let element_class_name = to_pascal_case(&spec.tag);
    logs::compiler!(
      "Extracted element metadata: <{}> -> {}Element",
      spec.tag,
      element_class_name
    );

    global_typings.push_str(&format!(
      "    \"{}\": import(\"./{}\").{}Element;\n",
      spec.tag,
      relative_path
        .to_string_lossy()
        .replace('\\', "/")
        .trim_end_matches(".js"),
      element_class_name
    ));
  }

  global_typings.push_str("  }\n}\n\nexport {};\n");
  std::fs::write(dist_types_dir.join("index.d.ts"), global_typings).ok();
  logs::success!("Type augmentation registry updated inside dist/types/index.d.ts");

  // Emit routes.json for all specs that declare a url pattern
  super::routes::emit(&specs, dist_types_dir.parent().unwrap_or(dist_types_dir));
}

fn parse_element_file(file_path: &Path, cm: &Arc<SourceMap>) -> Option<ExtractedSpec> {
  let fm = match cm.load_file(file_path) {
    Ok(f) => f,
    Err(_) => return None,
  };

  let lexer = Lexer::new(
    Syntax::Es(Default::default()),
    Default::default(),
    StringInput::from(&*fm),
    None,
  );

  let mut parser = Parser::new_from(lexer);
  let program = match parser.parse_program() {
    Ok(p) => p,
    Err(_) => return None,
  };

  // Run immutability lint check
  let mut lint_visitor = ImmutabilityVisitor {
    store_vars: std::collections::HashSet::new(),
    file_name: file_path.to_string_lossy().to_string(),
  };
  program.visit_with(&mut lint_visitor);

  let mut visitor = ElementVisitor::default();
  program.visit_with(&mut visitor);

  visitor.spec
}

#[derive(Default)]
struct ElementVisitor {
  spec: Option<ExtractedSpec>,
}

impl Visit for ElementVisitor {
  fn visit_call_expr(&mut self, call: &CallExpr) {
    if self.spec.is_some() {
      return;
    }

    if let Callee::Expr(expr) = &call.callee {
      match &**expr {
        // Member calls: ui.element(...) / ui.container(...)
        Expr::Member(member) => {
          if let (Expr::Ident(obj), MemberProp::Ident(prop)) = (&*member.obj, &member.prop) {
            if obj.sym == "ui" && (prop.sym == "element" || prop.sym == "container") {
              let kind = if prop.sym == "container" { "container" } else { "element" };
              self.capture(kind, call);
            }
          }
        }
        // Top-level definition calls: page() / dock() / view() / part()
        Expr::Ident(ident) => {
          let kind = match ident.sym.as_ref() {
            "page" => Some("page"),
            "dock" => Some("dock"),
            "view" => Some("view"),
            "part" => Some("part"),
            _ => None,
          };
          if let Some(kind) = kind {
            self.capture(kind, call);
          }
        }
        _ => {}
      }
    }

    call.visit_children_with(self);
  }
}

impl ElementVisitor {
  /// Builds an ExtractedSpec from a definition call of the given kind.
  ///
  /// The first argument and tag source depend on the kind:
  ///   page(route, config)  -> url = route,  tag = config.tag
  ///   dock(name, config)   -> tag = config.tag || "dock-" + name, parent = config.parent
  ///   view(tag, config)    -> tag = first arg
  ///   part(tag, config)    -> tag = first arg
  ///   ui.element(tag, ...) -> tag = first arg
  ///   ui.container(tag,..) -> tag = first arg
  fn capture(&mut self, kind: &str, call: &CallExpr) {
    if call.args.len() < 2 {
      return;
    }

    let first = get_string_literal(&call.args[0].expr);

    let mut spec = ExtractedSpec {
      tag: String::new(),
      kind: kind.to_string(),
      props: HashMap::new(),
      methods: Vec::new(),
      url: None,
      container: None,
      via: Vec::new(),
      parent: None,
      meta: HashMap::new(),
    };

    // For a page, the first argument is the route pattern.
    if kind == "page" {
      spec.url = first.clone();
    }

    if let Expr::Object(obj_lit) = &*call.args[1].expr {
      parse_spec_object(obj_lit, &mut spec);
    }

    // A page's render target is the last container in its `via` chain unless an
    // explicit `container` was given.
    if kind == "page" && spec.container.is_none() {
      if let Some(last) = spec.via.last() {
        spec.container = Some(last.clone());
      }
    }

    // Resolve the tag per kind.
    match kind {
      "page" | "dock" | "container" | "element" => {
        // page/dock take tag from config; fall back for dock.
        if spec.tag.is_empty() {
          if kind == "dock" {
            if let Some(name) = &first {
              spec.tag = format!("dock-{}", name);
            }
          } else if kind != "page" {
            // ui.element/ui.container take tag from the first argument.
            if let Some(t) = &first {
              spec.tag = t.clone();
            }
          }
        }
      }
      "view" | "part" => {
        if let Some(t) = &first {
          spec.tag = t.clone();
        }
      }
      _ => {}
    }

    if !spec.tag.is_empty() {
      self.spec = Some(spec);
    }
  }
}

fn get_string_literal(expr: &Expr) -> Option<String> {
  match expr {
    Expr::Lit(Lit::Str(s)) => {
      let str_val = s.value.as_str()?;
      Some(str_val.to_string())
    }
    _ => None,
  }
}

fn parse_spec_object(obj: &ObjectLit, spec: &mut ExtractedSpec) {
  for prop in &obj.props {
    if let PropOrSpread::Prop(p) = prop {
      if let Prop::KeyValue(kv) = &**p {
        if let PropName::Ident(key) = &kv.key {
          if key.sym == "props" {
            if let Expr::Object(props_obj) = &*kv.value {
              parse_props(props_obj, spec);
            }
          } else if key.sym == "methods" {
            // `methods` may be an object map (legacy) or, under the new defs,
            // helpers live under `on`. Both forms collect method names.
            if let Expr::Object(methods_obj) = &*kv.value {
              parse_methods(methods_obj, spec);
            }
          } else if key.sym == "on" {
            if let Expr::Object(on_obj) = &*kv.value {
              parse_methods(on_obj, spec);
            }
          } else if key.sym == "tag" {
            if let Some(t) = get_string_literal(&kv.value) {
              spec.tag = t;
            }
          } else if key.sym == "url" {
            spec.url = get_string_literal(&kv.value);
          } else if key.sym == "container" {
            spec.container = get_string_literal(&kv.value);
          } else if key.sym == "via" {
            if let Expr::Array(arr) = &*kv.value {
              for el in arr.elems.iter().flatten() {
                if let Some(name) = get_string_literal(&el.expr) {
                  spec.via.push(name);
                }
              }
            }
          } else if key.sym == "parent" {
            spec.parent = get_string_literal(&kv.value);
          } else if key.sym == "meta" {
            if let Expr::Object(meta_obj) = &*kv.value {
              parse_meta(meta_obj, spec);
            }
          }
        }
      }
    }
  }
}

fn parse_props(obj: &ObjectLit, spec: &mut ExtractedSpec) {
  for prop in &obj.props {
    if let PropOrSpread::Prop(p) = prop {
      if let Prop::KeyValue(kv) = &**p {
        if let PropName::Ident(key) = &kv.key {
          let prop_name = key.sym.to_string();
          let mut config = PropConfig::default();

          if let Expr::Object(config_obj) = &*kv.value {
            for c_prop in &config_obj.props {
              if let PropOrSpread::Prop(cp) = c_prop {
                if let Prop::KeyValue(ckv) = &**cp {
                  if let PropName::Ident(ckey) = &ckv.key {
                    if ckey.sym == "type" {
                      if let Expr::Ident(type_ident) = &*ckv.value {
                        config.prop_type = type_ident.sym.to_string();
                      }
                    } else if ckey.sym == "reflect" {
                      if let Expr::Lit(Lit::Bool(b)) = &*ckv.value {
                        config.reflect = b.value;
                      }
                    } else if ckey.sym == "state" {
                      if let Expr::Lit(Lit::Bool(b)) = &*ckv.value {
                        config.state = b.value;
                      }
                    } else if ckey.sym == "default" {
                      config.default = Some("any".to_string());
                    }
                  }
                }
              }
            }
          }

          spec.props.insert(prop_name, config);
        }
      }
    }
  }
}

fn parse_methods(obj: &ObjectLit, spec: &mut ExtractedSpec) {
  for prop in &obj.props {
    if let PropOrSpread::Prop(p) = prop {
      match &**p {
        Prop::KeyValue(kv) => {
          if let PropName::Ident(key) = &kv.key {
            spec.methods.push(key.sym.to_string());
          }
        }
        Prop::Method(m) => {
          if let PropName::Ident(key) = &m.key {
            spec.methods.push(key.sym.to_string());
          }
        }
        _ => {}
      }
    }
  }
}

fn parse_meta(obj: &ObjectLit, spec: &mut ExtractedSpec) {
  for prop in &obj.props {
    if let PropOrSpread::Prop(p) = prop {
      if let Prop::KeyValue(kv) = &**p {
        if let PropName::Ident(key) = &kv.key {
          if let Some(val) = get_string_literal(&kv.value) {
            spec.meta.insert(key.sym.to_string(), val);
          }
        }
      }
    }
  }
}

fn generate_dts_content(spec: &ExtractedSpec) -> String {
  let mut content = String::new();
  let class_name = to_pascal_case(&spec.tag);

  content.push_str(&format!(
    "/* Auto-generated definition for <{}>. Do not edit. */\n\n",
    spec.tag
  ));
  content.push_str(&format!(
    "export interface {}Element extends HTMLElement {{\n",
    class_name
  ));

  // Properties typing mapping
  for (name, config) in &spec.props {
    let ts_type = match config.prop_type.as_str() {
      "Boolean" => "boolean",
      "Number" => "number",
      "String" => "string",
      _ => "any",
    };
    content.push_str(&format!("  {}: {};\n", name, ts_type));
  }

  // Methods typing mapping
  for method in &spec.methods {
    content.push_str(&format!("  {}(...args: any[]): any;\n", method));
  }

  // A dock exposes the router-driven swap method for content replacement.
  if spec.kind == "dock" {
    content.push_str("  swap(el: HTMLElement, options?: { direction?: string }): Promise<void>;\n");
  }

  content.push_str("}\n");
  content
}

fn to_pascal_case(s: &str) -> String {
  let mut result = String::new();
  let mut capitalize = true;
  for c in s.chars() {
    if c == '-' {
      capitalize = true;
    } else if capitalize {
      result.push(c.to_ascii_uppercase());
      capitalize = false;
    } else {
      result.push(c);
    }
  }
  // Remove "Ui" prefix from start if it starts with "Ui"
  if result.starts_with("Ui") {
    result.split_off(2)
  } else {
    result
  }
}

struct ImmutabilityVisitor {
  store_vars: std::collections::HashSet<String>,
  file_name: String,
}

impl Visit for ImmutabilityVisitor {
  fn visit_var_declarator(&mut self, node: &VarDeclarator) {
    if let Some(init) = &node.init {
      if let Expr::Call(call) = &**init {
        if let Callee::Expr(callee_expr) = &call.callee {
          if let Expr::Member(member) = &**callee_expr {
            if let MemberProp::Ident(prop) = &member.prop {
              if prop.sym == "get" {
                if let Pat::Ident(binding) = &node.name {
                  self.store_vars.insert(binding.id.sym.to_string());
                }
              }
            }
          }
        }
      }
    }
    node.visit_children_with(self);
  }

  fn visit_assign_expr(&mut self, node: &AssignExpr) {
    if let AssignTarget::Simple(simple) = &node.left {
      if let SimpleAssignTarget::Member(member) = simple {
        if let Expr::Ident(obj_ident) = &*member.obj {
          if self.store_vars.contains(&obj_ident.sym.to_string()) {
            logs::warn!(
							"Immutability Violation in {}: mutating property '{}' of store-retrieved variable '{}' directly. Use store.set() instead.",
							self.file_name,
							get_member_prop_name(&member.prop),
							obj_ident.sym
						);
          }
        }
      }
    }
    node.visit_children_with(self);
  }

  fn visit_update_expr(&mut self, node: &UpdateExpr) {
    if let Expr::Member(member) = &*node.arg {
      if let Expr::Ident(obj_ident) = &*member.obj {
        if self.store_vars.contains(&obj_ident.sym.to_string()) {
          logs::warn!(
						"Immutability Violation in {}: updating property '{}' of store-retrieved variable '{}' directly. Use store.set() instead.",
						self.file_name,
						get_member_prop_name(&member.prop),
						obj_ident.sym
					);
        }
      }
    }
    node.visit_children_with(self);
  }
}

fn get_member_prop_name(prop: &MemberProp) -> String {
  match prop {
    MemberProp::Ident(id) => id.sym.to_string(),
    _ => "?".to_string(),
  }
}
